-- 1. List all tables in PUBLIC schema
SHOW TABLES IN SCHEMA PC_HEVODATA_DB.PUBLIC;

-- 2. Validate row counts for each raw table
SELECT 'CUSTOMERS_RAW' AS table_name, COUNT(*) AS row_count
FROM PC_HEVODATA_DB.PUBLIC.CUSTOMERS_RAW;
SELECT 'ORDERS_RAW' AS table_name, COUNT(*) AS row_count
FROM PC_HEVODATA_DB.PUBLIC.ORDERS_RAW;
SELECT 'PRODUCTS_RAW' AS table_name, COUNT(*) AS row_count
FROM PC_HEVODATA_DB.PUBLIC.PRODUCTS_RAW;
SELECT 'COUNTRY_DIM' AS table_name, COUNT(*) AS row_count
FROM PC_HEVODATA_DB.PUBLIC.COUNTRY_DIM;

-- 3. Preview sample data
SELECT * FROM PC_HEVODATA_DB.PUBLIC.CUSTOMERS_RAW LIMIT 5;
SELECT * FROM PC_HEVODATA_DB.PUBLIC.ORDERS_RAW LIMIT 5;
SELECT * FROM PC_HEVODATA_DB.PUBLIC.PRODUCTS_RAW LIMIT 5;
SELECT * FROM PC_HEVODATA_DB.PUBLIC.COUNTRY_DIM LIMIT 5;
