UPDATE PC_HEVODATA_DB.PUBLIC.FINAL_DATASET
SET email = 'Invalid Customer'
WHERE customer_id IS NULL
   OR (email IS NULL AND phone IS NULL AND country_code IS NULL);

SELECT * FROM PC_HEVODATA_DB.PUBLIC.FINAL_DATASET LIMIT 20;
